### ISSUE TITLE
Thief 摸鱼神器问题说明

### ISSUE THREAD

**Issue by sanjinhub** [cteamx/Thief#114]
**任何问题都可以去官方文档查看**

[https://hub.thief.im/docs](https://hub.thief.im/docs)

====================

Thief 推出了 Pro 版本更加好用

欢迎━(*｀∀´*)ノ亻! 摸鱼小伙伴试用。

====================

官网：[https://thief.im](https://thief.im)
社区：[https://hub.thief.im](https://hub.thief.im)

**Comment by sibaiabis** [comment]
社区网址挂了吧

**Comment by sanjinhub** [comment]
已经关站，目前没有社区了，官网：thief.im
在 2023年4月24日 +0800 09:23，sibaiabis ***@***.***>，写道：

**Comment by sibaiabis** [comment]
> 已经关站，目前没有社区了，官网：thief.im 在 2023年4月24日 +0800 09:23，sibaiabis ***@***.***>，写道：
> […](#)
> 社区网址挂了吧 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

![image](https://user-images.githubusercontent.com/32796170/234149487-230e9921-8ce8-4232-a514-1092016fe6d8.png)
这不502了么
