### ISSUE TITLE
越做越回去

### ISSUE THREAD

**Issue by vitasapple** [cteamx/Thief#124]
早起的版本，老板键是有用的，而且也不会动不动卡死，现在mac上面老板键屌用没有，而且时不时卡死，想要用鼠标点击退出都要卡半天，这特么哪里是摸鱼啊，这简直就是送命软件。如果要赚钱可以阉割功能啊，又不是不能接受，搞这种小动作干什么都不知道

**Comment by sanjinhub** [comment]
有没有可能真的是 BUG？
